<?xml version="1.0"?>



<robot xmlns:xacro="https://www.ros.org/wiki/xacro">
    <xacro:property name="M_PI" value="3.1415926535897931" />

    <xacro:property name="shoulder_mass" value="2"/>
    <xacro:property name="shoulder_r" value="0.1"/>
    <xacro:property name="shoulder_l" value="0.1"/>

    <xacro:property name="upper_arm_mass" value="0.4"/>
    <xacro:property name="upper_arm_r" value="0.05"/>
    <xacro:property name="upper_arm_l" value="0.4"/>

    <xacro:property name="elbow_mass" value="0.4"/>
    <xacro:property name="elbow_r" value="0.05"/>
    <xacro:property name="elbow_l" value="0.2"/>

    <xacro:property name="lower_arm_mass" value="0.2"/>
    <xacro:property name="lower_arm_r" value="0.04"/>
    <xacro:property name="lower_arm_l" value="0.2"/>

    <xacro:property name="wrist_mass" value="0.1"/>
    <xacro:property name="wrist_r" value="0.02"/>
    <xacro:property name="wrist_l" value="0.02"/>

    <xacro:macro name="manipulator" params="parent name:=manipulator *origin">
        <joint name="${parent}-${name}_shoulder" type="revolute">
            <xacro:insert_block name="origin" />
            <parent link="${parent}"/>
            <child link="${name}_shoulder"/>
            <limit lower="${-19*M_PI/20}" upper="${19*M_PI/20}" effort="50" velocity="${M_PI}"/>
            <axis xyz="0 0 1"/>
        </joint>

        <link name="${name}_shoulder">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${shoulder_l}" radius="${shoulder_r}"/>
                </geometry>
                <material name="orange"/>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <geometry>
                    <cylinder length="${shoulder_l}" radius="${shoulder_r}"/>
                </geometry>
            </collision>
            <inertial>
				<mass value="${shoulder_mass}" />
				<origin xyz="0 0 0" />
				<inertia ixx="${1/12*shoulder_mass*(3*shoulder_r*shoulder_r+shoulder_l*shoulder_l)}" ixy="0" ixz="0" iyy="${1/12*shoulder_mass*(3*shoulder_r*shoulder_r+shoulder_l*shoulder_l)}" iyz="0" izz="${1/2*shoulder_mass*shoulder_r*shoulder_r}"/>
			</inertial>
		</link>

        <joint name="${name}_shoulder-${name}_upper_arm" type="revolute">
            <origin rpy="0 0 0" xyz="0 0 ${shoulder_l/2}"/>
            <parent link="${name}_shoulder"/>
            <child link="${name}_upper_arm"/>
            <limit lower="${-M_PI/6}" upper="${7*M_PI/12}" effort="50" velocity="${M_PI}"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${name}_upper_arm">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${upper_arm_l/2}"/>
                <geometry>
                    <cylinder length="${upper_arm_l}" radius="${upper_arm_r}"/>
                </geometry>
                <material name="orange"/>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${upper_arm_l/2}" />
                <geometry>
                    <cylinder length="${upper_arm_l}" radius="${upper_arm_r}"/>
                </geometry>
            </collision>
            <inertial>
				<mass value="${upper_arm_mass}" />
				<origin xyz="0 0 0" />
				<inertia ixx="${1/12*upper_arm_mass*(3*upper_arm_r*upper_arm_r+upper_arm_l*upper_arm_l)}" ixy="0" ixz="0" iyy="${1/12*upper_arm_mass*(3*upper_arm_r*upper_arm_r+upper_arm_l*upper_arm_l)}" iyz="0" izz="${1/2*upper_arm_mass*upper_arm_r*upper_arm_r}"/>
			</inertial>
		</link>

        <!-- <joint name="camera_holder-camera_body" type="revolute">
            <origin rpy="0 0 0" xyz="0 0 ${holder_l/2+camera_height/2}"/>
            <parent link="camera_holder"/>
            <child link="camera_body"/>
            <limit lower="${-M_PI/6}" upper="${M_PI/12}" effort="50" velocity="${M_PI}"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="camera_body">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="${camera_depth} ${camera_width} ${camera_height}" />
				</geometry>
                <color rgba="0.5 0.5 0.5 1"/>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
                    <box size="${camera_depth} ${camera_width} ${camera_height}" />
				</geometry>
			</collision>
            <inertial>
				<mass value="${camera_mass}" />
				<origin xyz="0 0 0" />
				<inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
			</inertial>
		</link>

        <joint name="camera_body-depth_frame" type="fixed">
            <origin xyz="${camera_depth/2} 0.0175 0.0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
            <parent link="camera_body" />
            <child link="camera_depth_frame"/>
        </joint>

        <link name="camera_depth_frame"/>

        <joint name="camera_body-depth_optical" type="fixed">
            <origin xyz="${camera_depth/2} 0.0175 0" rpy="0 0 0" />
            <parent link="camera_body" />
            <child link="camera_depth_optical"/>
        </joint>

        <link name="camera_depth_optical"/>

    </xacro:macro>


    <xacro:macro name="rgbd_camera_gazebo_plugin_macro" params="link_name camera_name:=camera frame_name">
        <gazebo reference="${link_name}">
            <sensor type="depth" name="${link_name}_camera">
                <update_rate>30</update_rate>
                <camera>
                    <horizontal_fov>${69.4 * M_PI/180.0}</horizontal_fov>
                    <image>
                        <format>B8G8R8</format>
                        <width>640</width>
                        <height>480</height>
                    </image>
                    <clip>
                        <near>0.3</near>
                        <far>10</far>
                    </clip>
                </camera>
                <plugin name="${link_name}_controller" filename="libgazebo_ros_openni_kinect.so">
                    <cameraName>${camera_name}</cameraName>
                    <imageTopicName>/${camera_name}/color/image_raw</imageTopicName>
                    <cameraInfoTopicName>/${camera_name}/color/camera_info</cameraInfoTopicName>
                    <depthImageTopicName>/${camera_name}/depth/image_raw</depthImageTopicName>
                    <depthImageInfoTopicName>/${camera_name}/depth/camera_info</depthImageInfoTopicName>
                    <pointCloudTopicName>/${camera_name}/depth/points</pointCloudTopicName>
                    <frameName>${frame_name}</frameName>
                </plugin>
            </sensor>
        </gazebo> -->
    </xacro:macro>

</robot>
