<?xml version="1.0"?>

<robot name="triwheeler" xmlns:xacro="https://www.ros.org/wiki/xacro" >

    <!-- Included URDF Files -->
    <xacro:include filename="$(find simbot_description)/urdf/triwheeler.urdf.xacro" />

    <!-- Instantiate triwheeler_base_macro once (has no parameters atm) -->
    <xacro:triwheeler_base_macro />
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/triwheeler</robotNamespace>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        </plugin>
    </gazebo>


    <!-- manipulator -->
    <xacro:include filename="$(find simbot_description)/urdf/manipulator.urdf.xacro" />
    <xacro:manipulator parent="chassis">
        <origin xyz="${2*chassis_x/5} 0.0 ${chassis_z/2+shoulder_0_l/2}" rpy="0 0 0"/>
    </xacro:manipulator>

    <!-- RGB-D camera -->
    <xacro:include filename="$(find simbot_description)/urdf/rgbd_camera.urdf.xacro" />
    <xacro:rgbd_camera parent="plate">
        <origin xyz="${6*plate_r/7} 0.0 ${plate_l/2+holder_l/2}" rpy="0 0 0"/>
    </xacro:rgbd_camera>

    <!-- laser range sensor -->
    <xacro:include filename="$(find simbot_description)/urdf/laser.urdf.xacro" />
    <xacro:laser parent="plate">
        <origin xyz="0.0 0.0 ${plate_l/2+stand_l/2}" rpy="0 0 0"/>
    </xacro:laser>

</robot>
